export const products = [
    //barbati
    {id: 1, name: 'BOSS bocanci de piele Nebular', price: 879.90, originalPrice: 1299.90, image: 'bocanci-boss.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 979.90 LEI', isFavorite: false, category: 'barbati', type:"bocanci"},
    {id: 2, name: "HUGO pantofi Urian", price: 769.90, originalPrice: 989.90, image: 'bocanci-hugo.png', description: 'Cel mai mic preț de la lansare: 890.90 LEI', isFavorite: false, category: 'barbati', type:"bocanci"},
    {id: 3, name: "Karl Lagerfeld sneakers din piele KAPRI MENS", price: 669.90, originalPrice: 1009.90, image: 'sneaker-kl.png', description: 'Cel mai mic preț de la lansare: 719.90 LEI', isFavorite: false, category: 'barbati', type:"sneaker"},
    {id: 4, name: "Calvin Klein Jeans ghete chelsea de piele EVA BOOT MID CHELSEA ICONIC DR", price: 599.90, originalPrice: 849.90, image: 'ghete-ck.png', description: 'Cel mai mic preț de la lansare: 629.90 LEI', isFavorite: false, category: 'barbati', type:"bocanci"},
    {id: 5, name: 'Tommy Hilfiger sneakers NEW RUNNER EVA MIX FLAG', price: 499.90, originalPrice: 499.90, image: 'sneaker-tommy.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 979.90 LEI', isFavorite: false, category: 'barbati', type:"sneaker"},
    {id: 6, name: "Guess sneakers ARONA", price: 548.90, originalPrice: 548.90, image: 'sneaker-guess.png', description: 'Cel mai mic preț de la lansare: 890.90 LEI', isFavorite: false, category: 'barbati', type:"sneaker"},
    {id: 7, name: "Polo Ralph Lauren sneakers Train 89", price: 729.90, originalPrice: 729.90, image: 'sneaker-polo.png', description: 'Cel mai mic preț de la lansare: 719.90 LEI', isFavorite: false, category: 'barbati', type:"sneaker"},
    {id: 8, name: "The North Face pantofi Back to Berkeley IV Leather", price: 699.90, originalPrice: 849.90, image: 'bocanci-north.png', description: 'Cel mai mic preț de la lansare: 629.90 LEI', isFavorite: false, category: 'barbati', type:"bocanci"},
    //femei
    {id: 9, name: 'Karl Lagerfeld cizme de piele KL TOWER', price: 779.90, originalPrice: 1279.90, image: 'ghete-kl.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 789.90 LEI', isFavorite: false, category: 'femei', type:"cizme"},
    {id: 10, name: "Vagabond Shoemakers cizme de piele VENDELA", price: 739.90, originalPrice: 979.90, image: 'ghete-vagabond.png', description: 'Cel mai mic preț de la lansare: 799.90 LEI', isFavorite: false, category: 'femei', type:"cizme"},
    {id: 11, name: 'Moon Boot cizme de iarna MB EVX LIGHT NYLON', price: 699.90, originalPrice: 869.90, image: 'moonboot.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 869.90 LEI', isFavorite: false, category: 'femei',type:"bocanci"},
    {id: 12, name: "Gant botine din piele intoarsa Wintly", price: 599.90, originalPrice: 829.90, image: 'botine-gant.png', description: 'Cel mai mic preț de la lansare: 669.90 LEI', isFavorite: false, category: 'femei', type:"bocanci"},
    {id: 13, name: 'BOSS sneakers din piele intoarsă Brenta', price: 1139.90, originalPrice: 1139.90, image: 'sneaker-boss.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 789.90 LEI', isFavorite: false, category: 'femei', type:"sneaker"},
    {id: 14, name: "Lauren Ralph Lauren balerini de piele Jayna", price: 619.90, originalPrice: 619.90, image: 'balerini-ralph.png', description: 'Cel mai mic preț de la lansare: 799.90 LEI', isFavorite: false, category: 'femei', type:"balerini"},
    {id: 15, name: 'New Balance sneakers din piele intoarsă 327', price: 611.90, originalPrice: 679.90, image: 'sneaker-nb.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 869.90 LEI', isFavorite: false, category: 'femei', type:"sneaker"},
    {id: 16, name: "UGG cizme de zapada din piele intoarsa Classic Mini Atherson", price: 929.90, originalPrice: 1079.90, image: 'cizme-UGG.png', description: 'Cel mai mic preț de la lansare: 669.90 LEI', isFavorite: false, category: 'femei', type:"bocanci"},
    //copii
    {id: 17, name: 'Adidas ghete de iarnă TERREX SNOW', price: 429.90, originalPrice: 579.90, image: 'adidas.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 459.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 18, name: "Puma cizme de iarnă SNOW FUN", price: 389.90, originalPrice: 529.90, image: 'puma.png', description: 'Cel mai mic preț de la lansare: 419.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 19, name: 'Columbia botine impermeabile WINTER FUN', price: 499.90, originalPrice: 649.90, image: 'columbia.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 519.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 20, name: "Geox ghete de piele RESPIRA KIDS", price: 459.90, originalPrice: 609.90, image: 'geox.png', description: 'Cel mai mic preț de la lansare: 489.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 21, name: 'Reebok ghete sport OUTDOOR ACTIVE', price: 379.90, originalPrice: 499.90, image: 'reebok.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 399.90 LEI', isFavorite: false, category: 'copii', type:"sneaker"},
    {id: 23, name: 'Skechers cizme termoizolate SNOW GLOW', price: 439.90, originalPrice: 589.90, image: 'skechers.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 459.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 21, name: 'Tommy Hilfiger cizme de iarna copii', price: 379.90, originalPrice: 499.90, image: 'cizme-tommy.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 399.90 LEI', isFavorite: false, category: 'copii', type:"bocanci"},
    {id: 23, name: 'adidas sneakers de piele întoarsă pentru copii GRAND COURT 00s', price: 439.90, originalPrice: 589.90, image: 'adidas-sneaker.png', description: 'Cel mai mic preț din ultimele 30 de zile înainte de reducere: 459.90 LEI', isFavorite: false, category: 'copii', type:"sneaker"},
];